onboarding = false

[theme]
name = "tokyo-night"
auto_switch = false

[keys]
prefix = "ctrl+a"
detach = ["prefix+q", "prefix+d"]

# Splits
split_vertical = 'prefix+\'
split_horizontal = "prefix+minus"

# Pane navigation
focus_pane_left = "prefix+h"
focus_pane_down = "prefix+j"
focus_pane_up = "prefix+k"
focus_pane_right = "prefix+l"
