tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "thoughtbot/formulae"
brew "cairo"
brew "cocoapods"
brew "fd"
brew "fzf"
brew "git"
brew "git-lfs"
brew "go"
brew "imagemagick@6", link: true
brew "jq"
brew "lame"
brew "libav"
brew "logrotate", restart_service: true
brew "luajit"
brew "mysql-client"
brew "node@10", link: true
brew "postgresql", restart_service: true
brew "rbenv"
brew "sox"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "watchman"
brew "wget"
brew "github/gh/gh"
brew "heroku/brew/heroku"
brew "thoughtbot/formulae/gitsh"
cask "font-hack-nerd-font"
cask "font-victor-mono"
cask "iterm2"
