#!/usr/bin/env zsh

set -e

# xcode-select --install
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Clone and set up the repo

cd ~
git clone https://github.com/snappy316/dotfiles.git .dotfiles
cd .dotfiles
git checkout dotbot # TEMPORARY until this is merged to `main`

# Run the dotbot install

PROFILES_DIR="profiles"
PROFILE=${1:-macos}
CONFIG="${PROFILES_DIR}/${PROFILE}/install.conf.yaml"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule sync --quiet --recursive
git submodule update --init --recursive

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-brew -c "${CONFIG}" "${@:2}"
