#!/usr/bin/env ruby

DOT_VERSION_FILE = ".dot-version".freeze
CURRENT_VERSION = Gem::Version.new("0.6.0")
LOCAL_VERSION =
  if File.exist?(DOT_VERSION_FILE)
    Gem::Version.new(File.read(DOT_VERSION_FILE).chomp)
  else
    File.open(DOT_VERSION_FILE, "w") { |f| f.write "0.0.0" }
    Gem::Version.new("0.0.0")
  end
CHANGELOG = [
  {
    version: Gem::Version.new("0.0.1"),
    commands: [
      "./install/common/symlink.sh",
    ],
    notes: [],
  },
  {
    version: Gem::Version.new("0.1.0"),
    commands: [
      "git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm",
    ],
    notes: [
      "To finish tpm install, source the `.tmux.conf` file, then hit `prefix + I` to fetch and source the plugins",
    ],
  },
  {
    version: Gem::Version.new("0.2.0"),
    commands: [
      "./install/common/symlink.sh",
    ],
    notes: [
      "To finish p10k configuration, source `.zshrc`, then run `exec zsh` to fully restart zsh",
    ],
  },
  {
    version: Gem::Version.new("0.2.1"),
    commands: [
      "./install/common/vim.sh",
      "./install/common/tmux.zsh",
    ],
    notes: [
      "Make sure to install new packages from Brewfile or `./install/ubuntu/apt.zsh`",
    ],
  },
  {
    version: Gem::Version.new("0.3.0"),
    commands: [
      "./install/common/symlink.sh",
    ],
    notes: [
      "Finish `fzf` installation by running `/usr/local/opt/fzf/install`",
      "Make sure `fd` is installed",
    ],
  },
  {
    version: Gem::Version.new("0.4.0"),
    commands: [
      "./install/common/vim.sh",
    ],
    notes: [],
  },
  {
    version: Gem::Version.new("0.5.0"),
    commands: [
      "brew bundle --no-upgrade",
      "./install/common/vim.sh",
    ],
    notes: [],
  },
  {
    version: Gem::Version.new("0.6.0"),
    commands: [
      "./install/common/vim.sh",
    ],
    notes: [],
  },
].freeze

if LOCAL_VERSION == CURRENT_VERSION
  puts "👍 Up-to-date!"
else
  puts "🔧 Upgrading from #{LOCAL_VERSION} to #{CURRENT_VERSION}..."
  commands = []
  notes = []

  CHANGELOG.each do |entry|
    if entry[:version] > LOCAL_VERSION
      commands << entry[:commands]
      notes << entry[:notes]
    end
  end

  commands.flatten!.compact!
  notes.flatten!.compact!

  commands.each do |cmd|
    puts "⚡ Running `#{cmd}`"
    system(cmd)
  end

  File.open(DOT_VERSION_FILE, "w") { |f| f.write CURRENT_VERSION }
  puts "✅ Upgraded to #{CURRENT_VERSION}!"

  unless notes.empty?
    puts "🗒  Post-upgrade notes:"
    notes.flatten.compact.each { |nt| puts "    - #{nt}" }
  end
end
