#!/usr/bin/env ruby

DOT_VERSION_FILE = ".dot-version"
CURRENT_VERSION = Gem::Version.new("3.0.0")
LOCAL_VERSION =
  if File.exist?(DOT_VERSION_FILE)
    Gem::Version.new(File.read(DOT_VERSION_FILE).chomp)
  else
    File.open(DOT_VERSION_FILE, "w") { |f| f.write "0.0.0" }
    Gem::Version.new("0.0.0")
  end
CHANGELOG = [
  {
    version: Gem::Version.new("1.0.0"),
    commands: [
      "echo 'step 1 of v1'",
      "echo 'step 2 of v1'",
      "echo 'step 3 of v1'",
      "echo 'step 4 of v1'",
    ]
  },
  {
    version: Gem::Version.new("2.0.0"),
    commands: [
      "echo 'step 1 of v2'",
      "echo 'step 2 of v2'",
      "echo 'step 3 of v2'",
      "echo 'step 4 of v2'",
    ]
  },
  {
    version: Gem::Version.new("3.0.0"),
    commands: [
      "echo 'step 1 of v3'",
      "echo 'step 2 of v3'",
      "echo 'step 3 of v3'",
      "echo 'step 4 of v3'",
    ]
  },
]

if LOCAL_VERSION == CURRENT_VERSION
  puts "Up-to-date!"
else
  puts "Upgrading from #{LOCAL_VERSION} to #{CURRENT_VERSION}..."
  commands = CHANGELOG.
    map { |entry| entry[:commands] if entry[:version] > LOCAL_VERSION }.
    flatten.
    compact

  commands.each { |cmd| system(cmd) }

  File.open(DOT_VERSION_FILE, "w") { |f| f.write CURRENT_VERSION }
  puts "Upgraded to #{CURRENT_VERSION}!"
end
