# macos-specific

# `brew tap ...`

# `brew install ...`
brew "cloudflared"
brew "uv" # personal-only: work already provisions uv at /usr/local/bin outside Homebrew

# `brew install --cask ...`
cask "bambu-studio"
cask "discord"
cask "tailscale" # the cask version includes the CLI; the regular `brew` version does not

# `mas install ...`
mas "Day One", id: 1055511498
