#!/bin/zsh

if read -q "choice?Do you need to send this GPG key to your cloud box? (y/N): "; then
  vared -p "What email address is associated with the GPG key? " -c email
  if [ -z "$email" ]; then
    echo "Aborting"
    return 1
  fi

  gpg --export --armor --output my-public-key.asc ${email}
  scp my-public-key.asc $(pco cloud-box ip):~/ && rm my-public-key.asc
  scp ~/.dotfiles/.gitconfig.local $(pco cloud-box ip):~/.dotfiles/.gitconfig.local

  echo "\nCopied to your cloud box. Run the following command on the cloud box to import and use the GPG key:"
  echo "\n\`gpg --import my-public-key.asc && rm my-public-key.asc\`"
  echo "\n\nThen, configure the SSH server: \`sudo vim /etc/ssh/sshd_config`\"
  echo "\nAdd the following line to the bottom: \`StreamLocalBindUnlink yes\`"
  echo "\nThen restart the SSH server: \`sudo /etc/init.d/ssh restart\`"
  echo "\n\nAlso, be sure to update the \`~/.ssh/config\` file with the new IP!"
fi
