#!/bin/bash

# Git and git-lfs
printf "Installing git and git-lfs"
sudo apt-get install git
if [ ! git-lfs -v ]; then
  echo "Git-lfs not installed"
fi
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
sudo apt-get install git-lfs
git lfs install
