#!/bin/bash

# Zsh
if [ -n "`$SHELL -c 'echo $ZSH_VERSION'`" ]; then
  # assume zsh - don't install zsh
  printf "ZSH already installed"
else
  # assume bash - install zsh
  printf "Installing and configuring ZSH..."
  sudo apt install zsh
fi

# Oh My Zsh
if [ ! -d ~/.oh-my-zsh ] ; then
  printf "Installing Oh My Zsh"
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# Symlink Zsh dotfiles
if ! [ -L ~/.zshrc ]; then
  printf "Symlinking zshrc"
  ln -svf ~/.dotfiles/zsh/.zshrc ~
fi
