#!/bin/bash

# Homebrew
./install/common/homebrew.sh
./install/ubuntu/homebrew.sh
./install/ubuntu/apt.zsh

# Zsh / Oh My Zsh
./install/ubuntu/zsh.sh
./install/common/oh-my-zsh.zsh

# Download dotfiles
./install/common/dotfiles.sh

# Vim
./install/ubuntu/vim.zsh
./install/common/vim.sh

# tmux
./install/ubuntu/tmux.zsh
./install/common/tmux.zsh

# Symlink regular dotfiles
./install/common/symlink.sh

# Restart zsh
./install/common/restart-zsh.sh
