#!/bin/bash 

./scripts/apt
./scripts/git
./scripts/docker
./scripts/dotfiles
./scripts/zsh
./scripts/rbenv
./scripts/nodejs


# PostgreSQL
sudo apt update
sudo apt install postgresql postgresql-contrib

# MySQL
sudo apt update
sudo apt install mysql-server
sudo mysql_secure_installation

# Redis

# OpenSSL

# tmux

# Vim
if ! [ -L ~/.vimrc ]; then
  printf "Symlinking Vim dotfiles"
  ln -sfv ~/.dotfiles/.vimrc ~
  ln -sfv ~/.dotfiles/.vim ~
fi

if [ ! -d ~/.vim/bundle/Vundle.vim ] ; then
  printf "Installing Vundle"
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

#printf "Updating Vim plugins"
#vim +PluginInstall +qall

# Restart zsh
# cd ~
printf "All done! Restarting zsh"
exec /bin/zsh
