#!/bin/bash

# Homebrew
./common/homebrew.sh
./ubuntu/homebrew.sh

# Zsh / Oh My Zsh
./ubuntu/zsh.sh
./common/oh-my-zsh.sh

# Download dotfiles
./common/dotfiles.sh

# Vim
./common/vim.sh

# Symlink regular dotfiles
./common/symlink.sh

# Restart zsh
./common/restart-zsh.sh
