# macos-specific

# `brew tap ...`
tap "xcodesorg/made"

# `brew install ...`
brew "cairo" # Vector graphics library with cross-device output support - apparently needed for Prince Serverless
brew "cocoapods" # Dependency manager for for Cocoa projects - CCA
brew "pinentry-mac" # Pinentry for GPG on Mac
brew "xcodes" # Best command-line tool to install and switch between multiple versions of Xcode

# `brew install --cask ...`
cask "asana"
cask "betterdisplay"
cask "nordlayer"
cask "notion"
cask "slack"
cask "tuple"
cask "zoom"
