#!/bin/zsh

echo "Setting up work stuff"

cat <<EOT >> ~/.dotfiles/zsh/zshrc.local
## PCO-specific
eval "\$(\$HOME/Code/pco/bin/pco init -)"
export MYSQL_PORT_3306_TCP_ADDR=127.0.0.1
export MYSQL_SLAVE_PORT_3306_TCP_ADDR=127.0.0.1
export MYSQL_SLAVE_PORT_3306_TCP_PORT=3307
export PATH=~/pco-box/bin:/usr/local/bin:\$PATH
EOT

source ~/.zshrc

echo "\nDone!"
