# `brew tap ...`
tap "github/gh"
tap "jesseduffield/lazygit"

# `brew install ...`
brew "direnv"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "go"
brew "gpg"
brew "lazygit"
brew "mas"
brew "neovim"
brew "opencode"
brew "ripgrep"
brew "the_silver_searcher"
brew "tmux"

# `brew install --cask ...`
cask "claude"
cask "cleanshot"
cask "fantastical"
cask "font-jetbrains-mono-nerd-font"
cask "font-hack-nerd-font"
cask "font-victor-mono"
cask "ghostty"
cask "obsidian"
cask "raycast"
cask "rapidapi"
cask "spotify"
cask "visual-studio-code"
cask "1password"
cask "1password-cli"

# `mas install ...`
mas "Amphetamine", id: 937984704
mas "Apple Configurator", id: 1037126344
mas "Bear", id: 1091189122
mas "Day One", id: 1055511498 # personal-only
